/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuildBoxRouteImport } from './routes/build-box'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CombosRouteImport } from './routes/combos'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedCouponsRouteImport } from './routes/_authenticated/coupons'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedFollowUpsRouteImport } from './routes/_authenticated/follow-ups'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated/guide'
import { Route as AuthenticatedManageCombosRouteImport } from './routes/_authenticated/manage-combos'
import { Route as AuthenticatedNewEnquiryRouteImport } from './routes/_authenticated/new-enquiry'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSeoManagerRouteImport } from './routes/_authenticated/seo-manager'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as CombosIndexRouteImport } from './routes/combos.index'
import { Route as CombosSlugRouteImport } from './routes/combos.$slug'
import { Route as AuthenticatedEnquiriesIndexRouteImport } from './routes/_authenticated/enquiries.index'
import { Route as AuthenticatedEnquiriesIdRouteImport } from './routes/_authenticated/enquiries.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildBoxRoute = BuildBoxRouteImport.update({
  id: '/build-box',
  path: '/build-box',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouponsRoute = AuthenticatedCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowUpsRoute = AuthenticatedFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageCombosRoute =
  AuthenticatedManageCombosRouteImport.update({
    id: '/manage-combos',
    path: '/manage-combos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewEnquiryRoute = AuthenticatedNewEnquiryRouteImport.update({
  id: '/new-enquiry',
  path: '/new-enquiry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeoManagerRoute = AuthenticatedSeoManagerRouteImport.update({
  id: '/seo-manager',
  path: '/seo-manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CombosIndexRoute = CombosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CombosRoute,
} as any)
const CombosSlugRoute = CombosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CombosRoute,
} as any)
const AuthenticatedEnquiriesIndexRoute =
  AuthenticatedEnquiriesIndexRouteImport.update({
    id: '/enquiries/',
    path: '/enquiries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnquiriesIdRoute =
  AuthenticatedEnquiriesIdRouteImport.update({
    id: '/enquiries/$id',
    path: '/enquiries/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/build-box': typeof BuildBoxRoute
  '/catalogue': typeof CatalogueRoute
  '/combos': typeof CombosRouteWithChildren
  '/enquiry': typeof EnquiryRoute
  '/track': typeof TrackRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/manage-combos': typeof AuthenticatedManageCombosRoute
  '/new-enquiry': typeof AuthenticatedNewEnquiryRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/seo-manager': typeof AuthenticatedSeoManagerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/combos/$slug': typeof CombosSlugRoute
  '/combos/': typeof CombosIndexRoute
  '/enquiries/$id': typeof AuthenticatedEnquiriesIdRoute
  '/enquiries/': typeof AuthenticatedEnquiriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/build-box': typeof BuildBoxRoute
  '/catalogue': typeof CatalogueRoute
  '/enquiry': typeof EnquiryRoute
  '/track': typeof TrackRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/manage-combos': typeof AuthenticatedManageCombosRoute
  '/new-enquiry': typeof AuthenticatedNewEnquiryRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/seo-manager': typeof AuthenticatedSeoManagerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/combos/$slug': typeof CombosSlugRoute
  '/combos': typeof CombosIndexRoute
  '/enquiries/$id': typeof AuthenticatedEnquiriesIdRoute
  '/enquiries': typeof AuthenticatedEnquiriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/build-box': typeof BuildBoxRoute
  '/catalogue': typeof CatalogueRoute
  '/combos': typeof CombosRouteWithChildren
  '/enquiry': typeof EnquiryRoute
  '/track': typeof TrackRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/coupons': typeof AuthenticatedCouponsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deals': typeof AuthenticatedDealsRoute
  '/_authenticated/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/_authenticated/guide': typeof AuthenticatedGuideRoute
  '/_authenticated/manage-combos': typeof AuthenticatedManageCombosRoute
  '/_authenticated/new-enquiry': typeof AuthenticatedNewEnquiryRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/seo-manager': typeof AuthenticatedSeoManagerRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/combos/$slug': typeof CombosSlugRoute
  '/combos/': typeof CombosIndexRoute
  '/_authenticated/enquiries/$id': typeof AuthenticatedEnquiriesIdRoute
  '/_authenticated/enquiries/': typeof AuthenticatedEnquiriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/build-box'
    | '/catalogue'
    | '/combos'
    | '/enquiry'
    | '/track'
    | '/audit-logs'
    | '/categories'
    | '/coupons'
    | '/dashboard'
    | '/deals'
    | '/follow-ups'
    | '/guide'
    | '/manage-combos'
    | '/new-enquiry'
    | '/payments'
    | '/products'
    | '/reports'
    | '/seo-manager'
    | '/settings'
    | '/combos/$slug'
    | '/combos/'
    | '/enquiries/$id'
    | '/enquiries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/build-box'
    | '/catalogue'
    | '/enquiry'
    | '/track'
    | '/audit-logs'
    | '/categories'
    | '/coupons'
    | '/dashboard'
    | '/deals'
    | '/follow-ups'
    | '/guide'
    | '/manage-combos'
    | '/new-enquiry'
    | '/payments'
    | '/products'
    | '/reports'
    | '/seo-manager'
    | '/settings'
    | '/combos/$slug'
    | '/combos'
    | '/enquiries/$id'
    | '/enquiries'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/build-box'
    | '/catalogue'
    | '/combos'
    | '/enquiry'
    | '/track'
    | '/_authenticated/audit-logs'
    | '/_authenticated/categories'
    | '/_authenticated/coupons'
    | '/_authenticated/dashboard'
    | '/_authenticated/deals'
    | '/_authenticated/follow-ups'
    | '/_authenticated/guide'
    | '/_authenticated/manage-combos'
    | '/_authenticated/new-enquiry'
    | '/_authenticated/payments'
    | '/_authenticated/products'
    | '/_authenticated/reports'
    | '/_authenticated/seo-manager'
    | '/_authenticated/settings'
    | '/combos/$slug'
    | '/combos/'
    | '/_authenticated/enquiries/$id'
    | '/_authenticated/enquiries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuildBoxRoute: typeof BuildBoxRoute
  CatalogueRoute: typeof CatalogueRoute
  CombosRoute: typeof CombosRouteWithChildren
  EnquiryRoute: typeof EnquiryRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-box': {
      id: '/build-box'
      path: '/build-box'
      fullPath: '/build-box'
      preLoaderRoute: typeof BuildBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coupons': {
      id: '/_authenticated/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AuthenticatedCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-ups': {
      id: '/_authenticated/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AuthenticatedFollowUpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-combos': {
      id: '/_authenticated/manage-combos'
      path: '/manage-combos'
      fullPath: '/manage-combos'
      preLoaderRoute: typeof AuthenticatedManageCombosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-enquiry': {
      id: '/_authenticated/new-enquiry'
      path: '/new-enquiry'
      fullPath: '/new-enquiry'
      preLoaderRoute: typeof AuthenticatedNewEnquiryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seo-manager': {
      id: '/_authenticated/seo-manager'
      path: '/seo-manager'
      fullPath: '/seo-manager'
      preLoaderRoute: typeof AuthenticatedSeoManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/combos/': {
      id: '/combos/'
      path: '/'
      fullPath: '/combos/'
      preLoaderRoute: typeof CombosIndexRouteImport
      parentRoute: typeof CombosRoute
    }
    '/combos/$slug': {
      id: '/combos/$slug'
      path: '/$slug'
      fullPath: '/combos/$slug'
      preLoaderRoute: typeof CombosSlugRouteImport
      parentRoute: typeof CombosRoute
    }
    '/_authenticated/enquiries/': {
      id: '/_authenticated/enquiries/'
      path: '/enquiries'
      fullPath: '/enquiries/'
      preLoaderRoute: typeof AuthenticatedEnquiriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enquiries/$id': {
      id: '/_authenticated/enquiries/$id'
      path: '/enquiries/$id'
      fullPath: '/enquiries/$id'
      preLoaderRoute: typeof AuthenticatedEnquiriesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedCouponsRoute: typeof AuthenticatedCouponsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRoute
  AuthenticatedFollowUpsRoute: typeof AuthenticatedFollowUpsRoute
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRoute
  AuthenticatedManageCombosRoute: typeof AuthenticatedManageCombosRoute
  AuthenticatedNewEnquiryRoute: typeof AuthenticatedNewEnquiryRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSeoManagerRoute: typeof AuthenticatedSeoManagerRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedEnquiriesIdRoute: typeof AuthenticatedEnquiriesIdRoute
  AuthenticatedEnquiriesIndexRoute: typeof AuthenticatedEnquiriesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedCouponsRoute: AuthenticatedCouponsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealsRoute: AuthenticatedDealsRoute,
  AuthenticatedFollowUpsRoute: AuthenticatedFollowUpsRoute,
  AuthenticatedGuideRoute: AuthenticatedGuideRoute,
  AuthenticatedManageCombosRoute: AuthenticatedManageCombosRoute,
  AuthenticatedNewEnquiryRoute: AuthenticatedNewEnquiryRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSeoManagerRoute: AuthenticatedSeoManagerRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedEnquiriesIdRoute: AuthenticatedEnquiriesIdRoute,
  AuthenticatedEnquiriesIndexRoute: AuthenticatedEnquiriesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CombosRouteChildren {
  CombosSlugRoute: typeof CombosSlugRoute
  CombosIndexRoute: typeof CombosIndexRoute
}

const CombosRouteChildren: CombosRouteChildren = {
  CombosSlugRoute: CombosSlugRoute,
  CombosIndexRoute: CombosIndexRoute,
}

const CombosRouteWithChildren =
  CombosRoute._addFileChildren(CombosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuildBoxRoute: BuildBoxRoute,
  CatalogueRoute: CatalogueRoute,
  CombosRoute: CombosRouteWithChildren,
  EnquiryRoute: EnquiryRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
